"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Search, ExternalLink, CheckCircle, XCircle, Clock } from "lucide-react"

interface QuoteRequest {
  id: string
  date: string
  supplier: string
  partNumber: string
  description: string
  estimatedCost: string
  moq: string
  leadTime: string
  status: string
  source: string
  agent: string
  subAgent: string
  requestedBy: string
  notes: string
}

export default function ActionsPage() {
  const [quoteRequests, setQuoteRequests] = useState<QuoteRequest[]>([])
  const [searchQuery, setSearchQuery] = useState("")
  const [selectedRequest, setSelectedRequest] = useState<QuoteRequest | null>(null)

  useEffect(() => {
    // Load quote requests from localStorage
    const loadRequests = () => {
      if (typeof window === 'undefined') return
      
      const stored = localStorage.getItem("quoteRequests")
      if (stored) {
        setQuoteRequests(JSON.parse(stored))
      }
    }

    loadRequests()

    // Poll for updates every 2 seconds
    const interval = setInterval(loadRequests, 2000)
    return () => clearInterval(interval)
  }, [])

  const filteredRequests = quoteRequests.filter(
    (req) =>
      req.supplier.toLowerCase().includes(searchQuery.toLowerCase()) ||
      req.partNumber.toLowerCase().includes(searchQuery.toLowerCase()) ||
      req.description.toLowerCase().includes(searchQuery.toLowerCase()),
  )

  const updateStatus = (id: string, newStatus: string) => {
    const updated = quoteRequests.map((req) => (req.id === id ? { ...req, status: newStatus } : req))
    setQuoteRequests(updated)
    if (typeof window !== 'undefined') {
      localStorage.setItem("quoteRequests", JSON.stringify(updated))
    }
  }

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "Approved":
        return <CheckCircle className="h-4 w-4 text-green-600" />
      case "Rejected":
        return <XCircle className="h-4 w-4 text-red-600" />
      default:
        return <Clock className="h-4 w-4 text-yellow-600" />
    }
  }

  const getStatusVariant = (status: string): "default" | "secondary" | "destructive" | "outline" => {
    switch (status) {
      case "Approved":
        return "default"
      case "Rejected":
        return "destructive"
      default:
        return "secondary"
    }
  }

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Actions</h1>
        <p className="text-muted-foreground">Track AI-generated quote requests and actions</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Quote Requests</CardTitle>
          <CardDescription>Requests generated by AI Assistant</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="mb-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search requests..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
          </div>

          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Request ID</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Supplier</TableHead>
                  <TableHead>Part Number</TableHead>
                  <TableHead>Est. Cost</TableHead>
                  <TableHead>Source</TableHead>
                  <TableHead>Agent</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredRequests.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={9} className="text-center text-muted-foreground py-8">
                      No quote requests yet. Use the AI Assistant to generate recommendations.
                    </TableCell>
                  </TableRow>
                ) : (
                  filteredRequests.map((request) => (
                    <TableRow key={request.id} className="cursor-pointer hover:bg-muted/50">
                      <TableCell className="font-medium">{request.id}</TableCell>
                      <TableCell>{new Date(request.date).toLocaleDateString()}</TableCell>
                      <TableCell>{request.supplier}</TableCell>
                      <TableCell>{request.partNumber}</TableCell>
                      <TableCell className="font-medium text-primary">{request.estimatedCost}</TableCell>
                      <TableCell>
                        <Badge variant="outline">{request.source}</Badge>
                      </TableCell>
                      <TableCell>
                        <div className="space-y-1">
                          <Badge variant="outline" className="text-xs">
                            {request.agent}
                          </Badge>
                          <br />
                          <Badge variant="outline" className="text-xs">
                            {request.subAgent}
                          </Badge>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          {getStatusIcon(request.status)}
                          <Badge variant={getStatusVariant(request.status)}>{request.status}</Badge>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-2">
                          <Button size="sm" variant="outline" onClick={() => setSelectedRequest(request)}>
                            <ExternalLink className="h-3 w-3" />
                          </Button>
                          {request.status === "Pending" && (
                            <>
                              <Button size="sm" onClick={() => updateStatus(request.id, "Approved")}>
                                Approve
                              </Button>
                              <Button
                                size="sm"
                                variant="destructive"
                                onClick={() => updateStatus(request.id, "Rejected")}
                              >
                                Reject
                              </Button>
                            </>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      <Dialog open={!!selectedRequest} onOpenChange={() => setSelectedRequest(null)}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Quote Request Details</DialogTitle>
            <DialogDescription>{selectedRequest?.id}</DialogDescription>
          </DialogHeader>
          {selectedRequest && (
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Supplier</label>
                  <p className="text-sm font-medium">{selectedRequest.supplier}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Part Number</label>
                  <p className="text-sm font-medium">{selectedRequest.partNumber}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Description</label>
                  <p className="text-sm">{selectedRequest.description}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Estimated Cost</label>
                  <p className="text-sm font-medium text-primary">{selectedRequest.estimatedCost}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">MOQ</label>
                  <p className="text-sm">{selectedRequest.moq}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Lead Time</label>
                  <p className="text-sm">{selectedRequest.leadTime}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Source</label>
                  <Badge variant="outline">{selectedRequest.source}</Badge>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Status</label>
                  <Badge variant={getStatusVariant(selectedRequest.status)}>{selectedRequest.status}</Badge>
                </div>
              </div>

              <div>
                <label className="text-sm font-medium text-muted-foreground">AI Analysis</label>
                <div className="mt-2 space-y-2">
                  <Badge variant="outline">{selectedRequest.agent}</Badge>
                  <Badge variant="outline" className="ml-2">
                    {selectedRequest.subAgent}
                  </Badge>
                </div>
              </div>

              <div>
                <label className="text-sm font-medium text-muted-foreground">Notes</label>
                <p className="text-sm mt-1">{selectedRequest.notes}</p>
              </div>

              <div>
                <label className="text-sm font-medium text-muted-foreground">Requested By</label>
                <p className="text-sm">{selectedRequest.requestedBy}</p>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
